project:
  type: website
  output-dir: docs

website:
  title: "Assignment 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: brite
    css: brite.css
    toc: true
    page-layout: full



